Repository octokit/octokit.js, pull requests merged in 2020-06, with the labels that each got.

#1748 Add CodeQL security scanning
  .github/workflows/codeql.yml
Labels: maintenance

#1750 feat: `actions.downloadJobLogsForWorkflowRun`, `actions.getJobForWorkflowRun`, `actions.listWorkflowRunsForRepo`, `actions.createInstallationAccessToken`, `apps.listReposAccessibleToInstallation`, `apps.revokeInstallationAccessToken`, `interactions.setRestrictionsForOrg`, `interactions.setRestrictionsForRepo`. Deprecates `actions.downloadWorkflowJobLogs`, `actions.getWorkflowJob`, `actions.listRepoWorkflowRuns`, `actions.createInstallationToken`, `apps.listRepos`, `apps.revokeInstallationToken`, `interactions.addOrUpdateRestrictionsForOrg`, `interactions.addOrUpdateRestrictionsForRepo`, `issues.replaceAllLabels`
  package-lock.json
  package.json
Labels: feature

#1755 feat: tons renamed endpoint methods, to align with according changes in docs
  package-lock.json
  package.json
  test/issues/881-redirect-url.test.ts
  test/scenarios/branch-protection.test.ts
  test/scenarios/create-file.test.ts
  test/scenarios/create-status.test.ts
  test/scenarios/get-archive.test.ts
  test/scenarios/get-content.test.ts
  test/scenarios/release-assets.test.ts
Labels: feature

#1760 v18 - removes all deprecated methods
  .github/workflows/test.yml
  docs/gatsby-config.js
  package-lock.json
  package.json
Labels: feature

#1770 fix(typescript): return type for `octokit.hook.wrap` callback
  index.d.ts
  scripts/update-endpoints/templates/index.d.ts.tpl
Labels: bug
