Repository octokit/octokit.js, pull requests merged in 2020-05, with the labels that each got.

#1704 docs: issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01_bug.md
  .github/ISSUE_TEMPLATE/02_feature.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#1712 build(deps): update `@types/node` to the latest version
  package-lock.json
  package.json
Labels: maintenance

#1714 fix(TypeScript): `octokit.gists.{create,update}({ gist_id, files })
  package-lock.json
  package.json
Labels: bug

#1716 fix: handle deprecated parameters
  package-lock.json
  package.json
Labels: bug

#1717 Replace Greenkeeper with Dependabot
  .github/dependabot.yml
  .github/workflows/test.yml
  README.md
Labels: maintenance

#1734 bug: style(docs): fix overflow-y in sections
  docs/src/components/api.module.css
Labels: bug, documentation
