Repository octokit/octokit.js, pull requests merged in 2021-04, with the labels that each got.

#21 fix(typescript): `octokit` instance types for `App` and `OAuthApp`
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  test/typescript-validate.ts
Labels: bug, typescript

#22 feat: initial version
  .github/ISSUE_TEMPLATE/01_bug.md
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-prettier.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  index.js
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  src/octokit.ts
  src/version.ts
  test/app.test.ts
  test/smoke.test.ts
  test/typescript-validate.ts
  tsconfig.json
Labels: feature

#26 docs(readme): missing .rest in app example
  README.md
Labels: bug, documentation

#23 docs(README): clarify the difference between `octokit.request` and the `octokit.rest.*` endpoint methods
  README.md
Labels: bug, documentation
