Repository octokit/octokit.js, pull requests merged in 2021-04, with the labels that each got.

#2081 ci: add NodeJS 16 to the test matrix
  .github/workflows/test.yml
Labels: maintenance

#2089 fix(README): correct typo in the spelling of "graphql"
  README.md
Labels: documentation, maintenance

#2080 fix(README): overall improvements
  README.md
Labels: awaiting response, documentation, maintenance

#2090 Update config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, documentation
