Repository octokit/octokit.js, pull requests merged in 2022-06, with the labels that each got.

#2224 fix: re-enable throttling plugin
  src/octokit.ts
  test/app.test.ts
Labels: bug

#2223 build(deps): lock file maintenance
  package-lock.json
  test/app.test.ts
Labels: maintenance

#2227 feat: new `octokit.rest.*` methods via `@octokit/plugin-rest-endpoint-methods@5.14.0`
  package-lock.json
  package.json
Labels: feature

#2229 Runs prettier on the security file
  SECURITY.md
  package-lock.json
  package.json
Labels: documentation, maintenance

#2231 fix: set correct user agent
  src/octokit.ts
Labels: bug

#2235 build(npm): replace 'pika' command with 'pika-pack'
  package.json
Labels: maintenance

#2236 Fix a typo
  README.md
Labels: documentation, maintenance
