Repository octokit/octokit.js, pull requests merged in 2022-07, with the labels that each got.

#2243 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: maintenance

#2248 fix(deps): update @octokit dependencies to their latest version
  package-lock.json
  package.json
Labels: dependencies, maintenance

#2257 fix(README): `getInstallationOctokit()` doesn't need destructuring
  README.md
Labels: bug, documentation

#2260 chore: fix typo in README
  README.md
Labels: bug, documentation
