Repository octokit/octokit.js, pull requests merged in 2022-09, with the labels that each got.

#2291 ci(workflow): fix test workflow to assure it is not skipped if test_matrix fails
  .github/workflows/test.yml
Labels: maintenance

#2297 docs: Fix incorrect import in code example
  README.md
Labels: documentation, maintenance

#2298 docs(README): fix `App` example
  README.md
Labels: bug, documentation

#2299 docs(README): fix preview GraphQL example
  README.md
Labels: bug, documentation

#2302 docs(README): add missing `await` statement to `getContent()` call
  README.md
Labels: bug, documentation
