Repository octokit/octokit.js, pull requests merged in 2023-07, with the labels that each got.

#2493 fix(deps): bump Octokit deps
  package-lock.json
  package.json
Labels: Type: Maintenance

#2456 feat: v3
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
Labels: Type: Feature, Type: Breaking change

#2502 docs(readme): add 'Fetch missing' section
  README.md
Labels: Type: Documentation

#2506 Add auto responder workflow
  .github/workflows/immediate-response.yml
Labels: Type: Maintenance

#2501 docs(readme): update Proxy Servers information
  README.md
Labels: Type: Documentation, Status: Blocked
