Repository octokit/octokit.js, pull requests merged in 2023-06, with the labels that each got.

#2476 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#2478 fix(deps): revert breaking changes
  package-lock.json
  package.json
Labels: Type: Maintenance

#2465 feat: add RequestError support
  README.md
  package-lock.json
  package.json
  src/index.ts
  src/octokit.ts
  test/smoke.test.ts
  test/typescript-validate.ts
Labels: Type: Feature
