Repository octokit/octokit.js, pull requests merged in 2023-05, with the labels that each got.

#2449 build: replace pika with esbuild and tsc
  package-lock.json
  package.json
  scripts/build.mjs
  tsconfig.json
Labels: Type: Maintenance

#2446 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Maintenance, Type: Breaking change

#2455 fix(revert): revert "fix(deps): update dependency @octokit/plugin-throttling to v6"
  package-lock.json
  package.json
Labels: Type: Bug

#2372 docs: remove previews
  README.md
Labels: Status: Blocked, Type: Maintenance, Type: Breaking change

#2457 Add additional thoughts on rolling out breaking changes
  MAINTAINING.md
Labels: Type: Documentation

#2458 docs(README): fix closing `<code>` tag
  README.md
Labels: Type: Documentation

#2460 fix(deps): upgrade `@octokit/app`
  package-lock.json
  package.json
Labels: Type: Bug
